name: Exécuter en python 3.7, 3.8, 3.9 et produire markdown

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7,3.8,3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Installe Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Installer les bibliothèques requises
      run: |
        python -m pip install --upgrade pip
        python -m pip install colorama
    - name: créer le fichier markdown
      run: python classifier.py elements-${{ matrix.python-version }}.md
    - name: Produire et charger le fichier
      uses: actions/upload-artifact@v2
      with:
        name: elements
        path: elements-${{ matrix.python-version }}.md